version: '3.8'

services:
  
  #http://localhost:5342/
  seq-server:
    image: datalust/seq:latest
    ports:
      - "5341:5341"
      - "5342:80"
    environment:
      - ACCEPT_EULA=Y
    restart: unless-stopped
  
  # http://127.0.0.1:9411/zipkin/
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - network
  
  patient-service:
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    image: publicaccount123/patient-service:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;http://+:443
    ports:
      - 7000:80
    networks:
      - network
  
  measurement-service:
    build:
      context: .
      dockerfile: MeasurementService/Dockerfile
    image: publicaccount123/measurement-service:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;http://+:443
    ports:
      - 7001:80
    networks:
      - network
        
  patient-ui:
    build:
      context: .
      dockerfile: patient-ui/Dockerfile
    ports:
      - 8080:8080

networks:
  network:
    name: network
    driver: bridge
