version: '3.8'
services: 
  patient-service:
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    image: publicaccount123/dls_assignment:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;http://+:443
    ports:
      - 7000:80
  
  measurement-service:
    build:
      context: .
      dockerfile: MeasurementService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;http://+:443
    ports:
      - 7001:80
      
      
networks:
  network:
    name: system-network
    driver: bridge
    