# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
        
  push-to-registry:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker images
        run: docker-compose build
        
      - name: Connect to DockerHub
        run: docker login -u publicaccount123 -p dckr_pat_mxlDyYHHTiDfkvhXWb0II2xOuRc
        
      - name: Push images to registry
        run: |
          services=$(docker-compose config --services)
          for image in $services; 
          do
          if docker inspect $image | grep -q '"push-to-registry": true'; then
            docker tag $image publicaccount123/$image:latest 
            docker push publicaccount123/$image:latest
          fi
          done 


        